# Generated by Django 4.0.1 on 2022-01-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=500, null=True, unique=True)),
                ('message', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('new_cases', models.IntegerField()),
                ('active_cases', models.IntegerField()),
                ('new_recovered', models.IntegerField()),
                ('currently_admitted', models.IntegerField()),
                ('new_tests_conducted', models.IntegerField()),
                ('new_discharges', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=500)),
                ('document_image', models.ImageField(default='doctor.jpg', upload_to='static/images')),
                ('document_url', models.FileField(upload_to='static/images')),
                ('document_published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Eventcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'Eventcategory',
            },
        ),
        migrations.CreateModel(
            name='Health_Priorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=500)),
                ('priority', models.IntegerField()),
                ('content_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Newsauthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_author', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'Newsauthor',
            },
        ),
        migrations.CreateModel(
            name='Mohevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('event_image', models.ImageField(null=True, upload_to='')),
                ('event_content', models.TextField(blank=True, max_length=1000, null=True)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Moh_profile.mohevents')),
                ('news_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='Moh_profile.mohevents')),
            ],
        ),
    ]
