# Generated by Django 3.2.6 on 2021-08-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moh_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
