# Generated by Django 3.2.6 on 2021-08-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Moh_profile', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cases', models.IntegerField()),
                ('cumulative_confirmed_cases', models.IntegerField()),
                ('active_cases', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('Currently_admitted_in_treatment_units', models.IntegerField()),
                ('New_discharges_from_treatment_units', models.IntegerField()),
                ('total_tests_conducted', models.IntegerField()),
                ('Total_deaths', models.IntegerField()),
                ('new_cases_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Priorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('content_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Mohevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('Content_url', models.CharField(max_length=300)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
