# Generated by Django 3.2.6 on 2021-08-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moh_profile', '0004_auto_20210830_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='mohevents',
            name='event_image',
            field=models.ImageField(default='doctor.jpg', upload_to=''),
        ),
    ]
