# Generated by Django 3.2.6 on 2021-09-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moh_profile', '0005_mohevents_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mohevents',
            old_name='Content_url',
            new_name='event_content',
        ),
    ]
