# Generated by Django 3.2.6 on 2021-09-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moh_profile', '0006_rename_content_url_mohevents_event_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid19',
            old_name='cumulative_confirmed_cases',
            new_name='currently_admitted',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='new_cases_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='currently_admitted_in_treatment_units',
            new_name='new_deaths',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='new_discharges_from_treatment_units',
            new_name='new_discharges',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='total_deaths',
            new_name='new_recovered',
        ),
        migrations.RenameField(
            model_name='covid19',
            old_name='total_recovered',
            new_name='new_tests_conducted',
        ),
        migrations.RemoveField(
            model_name='covid19',
            name='total_tests_conducted',
        ),
    ]
