# Generated by Django 3.2.8 on 2021-10-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moh_profile', '0007_auto_20210907_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='mohevents',
            name='event_image',
            field=models.ImageField(default='doctor.jpg', upload_to='static/images'),
        ),
    ]
