# Generated by Django 3.2.8 on 2021-11-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moh_profile', '0009_alter_person_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
