# Generated by Django 3.2.8 on 2021-12-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moh_profile', '0011_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mohevents',
            name='event_content',
            field=models.TextField(max_length=1000),
        ),
    ]
