# Generated by Django 3.2.8 on 2021-12-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moh_profile', '0012_alter_mohevents_event_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mohevents',
            name='event_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
