# Generated by Django 3.2.8 on 2021-12-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moh_profile', '0013_alter_mohevents_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(max_length=50)),
            ],
        ),
    ]
